### ISSUE TITLE
🐛 Le Menu Ait Kolé A Drwat

### ISSUE THREAD

**Issue by Mateo-Blueberry** [Blueberry-Pictures/blueberrypictures.fr#6]
**Describe the bug**

Le menu est malheureusement collé à droite, il n’y a donc aucun espace entre le menu et la droite.

**To Reproduce**
1. Go to droite
2. Open the yeux
3. Constater the problemz
4. S’alarmer

**Expected behavior**
J’aimerais, si possible, que le menu collé à droite ne soit plus collé à droite mais reste un menu. Juste un menu. Pas un menu collé à droite.

**Screenshots**
Je n’en ai pas, mais il suffit d’imaginer un menu normal mais collé à droite.

**Desktop (please complete the following information):**
 - Non mais partout en fait.

**Smartphone (please complete the following information):**
 - En mode paysage seulement mais kaslécouill quand même.

**Additional context**
Non, ca va.

**Comment by YoruKiwi** [comment]
Fixed!
