### ISSUE TITLE
💄 Enhance UI

### ISSUE THREAD

**Issue by Mateo-Blueberry** [Blueberry-Pictures/blueberrypictures.fr#7]
GLOBAL
- Masquer le menu tant qu'il n'y a que la homepage
- Scroll snap + behavior smooth

Section 2
- Augmenter la marge minimum entre le bas du texte de présentation et le bord de la section
- Assombrir le texte de présentation Blueberry
- Justifier le texte

Section 3
- Texte à ancrer en bas de la section

**Comment by NoaSecond** [comment]
Fixed!
