### ISSUE TITLE
🌐 Remplacement textes

### ISSUE THREAD

**Issue by Mateo-Blueberry** [Blueberry-Pictures/blueberrypictures.fr#8]
Section 2:
- Changer l'avis de Djebril pour:
"Blueberry a le sens du professionnalisme et du détail. Mateo et son équipe ont apporté une qualité exceptionnelle à la hauteur de mes exigences. Let the show begin…"

Section 3:
- "watch more videos" devient "watch video" / "voir le clip"
- "Derniers travaux" devient "dernier projet"
- corriger le Lorem Ipsum

Footer:
- Textes en minuscule
- Personal data sans "s"

**Comment by NoaSecond** [comment]
Chef, corriger le Lorem Ipsum par quoi ?

**Comment by Mateo-Blueberry** [comment]
La bonne version du texte en français se trouve dans la version anglaise de la page. Pour la version anglaise: « May 2024, directed by Mateo Mauri-Second »MerciiiiSent from my iPhoneOn 17 Jul 2024, at 9:12 AM, 𝕭𝖗𝖚𝖒𝖊 ***@***.***> wrote:﻿
@Mateo-Blueberry , corriger le Lorem Ipsum par quoi ?
